namespace MolvenoCLI;

/// <summary>
/// The default SQLite environment for RestaurantApp. This mirrors the
/// <c>RestaurantApp/.env.docker</c> file the container ships with and is written
/// out by <c>molveno env</c> and used as the fallback by <c>molveno run</c>.
/// </summary>
internal static class EnvTemplate
{
    public const string Sqlite =
        """
        # ─────────────────────────────────────────────────────────────────────────────
        # RestaurantApp environment (generated by `molveno env`).
        # Pass a copy of this file to `molveno run --env=<path>` to customise the run.
        # Defaults below start the app on SQLite with no extra services.
        # ─────────────────────────────────────────────────────────────────────────────

        APP_NAME=RestaurantApp
        APP_ENV=local
        APP_KEY=base64:cx50zovZRymA73PzhI9iE/0LYri/EifLvezalppjQFI=
        APP_DEBUG=true
        APP_URL=http://localhost:8000

        APP_TIMEZONE=Europe/Amsterdam
        APP_LOCALE=en
        APP_FALLBACK_LOCALE=en
        APP_FAKER_LOCALE=en_US

        # Host port published to the machine (the container always serves on 8000).
        APP_PORT=8000

        # ─── Database ────────────────────────────────────────────────────────────────
        # Default: SQLite. The container creates the file and seeds it on first boot.
        # DB_DATABASE must be an absolute path inside the container for SQLite.
        DB_CONNECTION=sqlite
        DB_DATABASE=/var/www/html/database/data/database.sqlite

        # Set DB_SEED=true to force a fresh migrate + seed on the next boot.
        DB_SEED=false

        # To use MySQL instead: set DB_CONNECTION=mysql, fill these in and run a
        # MySQL container reachable at DB_HOST.
        # DB_CONNECTION=mysql
        # DB_HOST=host.docker.internal
        # DB_PORT=3306
        # DB_DATABASE=restaurantapp
        # DB_USERNAME=restaurantapp
        # DB_PASSWORD=secret

        # ─── Drivers (database-backed, work out of the box on SQLite) ────────────────
        SESSION_DRIVER=database
        SESSION_LIFETIME=30
        SESSION_ENCRYPT=true
        SESSION_PATH=/
        SESSION_DOMAIN=null

        QUEUE_CONNECTION=database
        CACHE_STORE=database
        BROADCAST_CONNECTION=log
        FILESYSTEM_DISK=local

        LOG_CHANNEL=stack
        LOG_STACK=single
        LOG_LEVEL=debug

        MAIL_MAILER=log

        BCRYPT_ROUNDS=12

        TAX_RATE=0.10
        """;

    /// <summary>
    /// Reads the value of a key from an env file's text. Returns null when the key
    /// is absent or commented out. Used to honour APP_PORT for port publishing.
    /// </summary>
    public static string? ReadValue(string envContents, string key)
    {
        foreach (var raw in envContents.Split('\n'))
        {
            var line = raw.Trim();
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var eq = line.IndexOf('=');
            if (eq <= 0)
            {
                continue;
            }

            if (line[..eq].Trim().Equals(key, StringComparison.OrdinalIgnoreCase))
            {
                return line[(eq + 1)..].Trim().Trim('"');
            }
        }

        return null;
    }
}
